/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118219-g551041e384-20250103"
#endif /* AVUTIL_FFVERSION_H */
